//регистрация
export const REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST" = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS" = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED: "REGISTER_USER_FAILED" = "REGISTER_USER_FAILED";

//авторизация
export const LOGIN_USER: "LOGIN_USER"= "LOGIN_USER";

export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const GET_USER_FAILED: "GET_USER_FAILED" = "GET_USER_FAILED";
export const GET_USER_REQUEST: "GET_USER_REQUEST" = "GET_USER_REQUEST";
export const LOGOUT_USER: "LOGOUT_USER"= "LOGOUT_USER";

export const ADD_VIEW_INGREDIENT: "ADD_VIEW_INGREDIENT" = "ADD_VIEW_INGREDIENT";
export const REMOVE_VIEW_INGREDIENT: "REMOVE_VIEW_INGREDIENT" = "REMOVE_VIEW_INGREDIENT";

// ингредиенты конструктора
export const ADD_INGREDIENTS_BURGER: "ADD_INGREDIENTS_BURGER" = "ADD_INGREDIENTS_BURGER";
export const ADD_BUN: "ADD_BUN" = "ADD_BUN";
export const DELETE_INGREDIENT_BURGER: "DELETE_INGREDIENT_BURGER" = "DELETE_INGREDIENT_BURGER";
export const UPDATE_INGREDIENTS_CONSTRUCTOR: "UPDATE_INGREDIENTS_CONSTRUCTOR" = "UPDATE_INGREDIENTS_CONSTRUCTOR";
export const CLEAR_INGREDIENTS_CONSTRUCTOR: "CLEAR_INGREDIENTS_CONSTRUCTOR" = "CLEAR_INGREDIENTS_CONSTRUCTOR";

// ингредиенты бургера
export const GET_ITEMS_REQUEST: "GET_ITEMS_REQUEST" = "GET_ITEMS_REQUEST";
export const GET_ITEMS_SUCCESS: "GET_ITEMS_SUCCESS" = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILED: "GET_ITEMS_FAILED" = "GET_ITEMS_FAILED";

// оформление заказа
export const GET_ORDERDETAILS_REQUEST: "GET_ORDERDETAILS_REQUEST" = "GET_ORDERDETAILS_REQUEST";
export const GET_ORDERDETAILS_SUCCESS: "GET_ORDERDETAILS_SUCCESS" = "GET_ORDERDETAILS_SUCCESS";
export const GET_ORDERDETAILS_FAILED: "GET_ORDERDETAILS_FAILED" = "GET_ORDERDETAILS_FAILED";
